language: python
python:
    - "2.7"
env:
    - PLATFORMIO_CI_SRC=src/
git: 
  submodules: false 
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
script:
    - platformio ci --project-conf ./platformio.ini
    - cd ./bootloader
    # Install ParseBasic interpreter version 0.1.0
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/NETponents/ParseBasic/v0.0.1/pb.py)" ./bootloader.pba
