Octoduino: lib/bootstrap/bootstrap.cpp File Reference
bootstrap.cpp File Reference
#include <Arduino.h>
#include <SD.h>
#include <SPI.h>
#include "pbparse.h"
#include "output.h"
Functions
void initBootstrap ()
Function Documentation
void initBootstrap (void)
Initializes the system to execute the main PB file
Definition at line 17 of file bootstrap.cpp.
References outwrite(), and PBstart().
Referenced by setup().
 {
   // Pre-req for SD class
   pinMode(10, OUTPUT);
   //Open SD card
   SD.begin(4);
   //Begin parsing the PARSEBASIC main script
   outwrite("Launching bootloader");
   PBstart("/boot.pba");
 }