Octoduino: Swap Class Reference
Swap Class Reference
#include <swap.h>
Static Public Member Functions
static void clearFolder (File fldr)
static void create (String name, String value)
static String GetPath (String name)
static void init ()
static String read (String name)
static void ready ()
static void sdelete (String name)
static void update (String name, String value)
Detailed Description
Definition at line 11 of file swap.h.
Member Function Documentation
void Swap::clearFolder (File fldr) static
Recursivly removes all files from within a folder, then deletes it and returns.
Definition at line 47 of file swap.cpp.
Referenced by init().
   {
     while(true)
     {
       File node = fldr.openNextFile();
       if(!node)
       {
         // No more files found in directory
         break;
       }
       else if(node.isDirectory())
       {
         Swap::clearFolder(node);
         SD.rmdir(node.name());
       }
       else
       {
         SD.remove(node.name());
       }
     }
   }
void Swap::create (String name, String value) static
Creates a new swap object and assigns it the given value.
Definition at line 83 of file swap.cpp.
References Crash::forceHalt(), GetPath(), and ready().
Referenced by Stack::init(), Parse::Opcode::System::SWAP::NEW(), and update().
   {
     // Make sure that the var name is 8.3 compliant
     if(name.length() > 8)
     {
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("Variable is not 8.0 compliant.");
       #else
         Crash::forceHalt("Ex017");
       #endif
     }
     // Make sure that swap is ready
     Swap::ready();
     // Check to see if variable already exists
     if(SD.exists(Swap::GetPath(name)))
     {
       // It does, so crash system
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("Tried to create a variable that already exists in swap.");
       #else
         Crash::forceHalt("Ex012");
       #endif
     }
     // Create new file handle for new swap file
     File newSwap = SD.open(Swap::GetPath(name), FILE_WRITE);
     // Check to see if we could open the file
     if (newSwap)
     {
       // Write value of item and close the handle
       newSwap.println(value);
       newSwap.close();
     }
     else
     {
       // IO error, crash the system
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("Error writing new swap variable to SD card.");
       #else
         Crash::forceHalt("Ex013");
       #endif
     }
   }
String Swap::GetPath (String name) static
Gets the full SWAP path of the requested variable.
Definition at line 71 of file swap.cpp.
Referenced by create(), read(), and sdelete().
   {
     // Add parts together
     String swp = "/swap/";
     String ext = ".swp";
     String result = swp + name + ext;
     // Return full filename
     return result;
   }
void Swap::init () static
Initializes the SWAP area on the SD card.
Definition at line 18 of file swap.cpp.
References clearFolder(), Crash::forceHalt(), and ready().
Referenced by Core::init().
   {
     // Check to see if swap exists
     if(SD.exists("/swap"))
     {
       // Attempt to remove it
       if(!SD.rmdir("/swap"))
       {
         // SWAP folder is not empty
         File root = SD.open("/swap/");
         Swap::clearFolder(root);
         if(SD.exists("/swap"))
         {
           #ifdef CRASH_MSG_DETAIL
             Crash::forceHalt("Swap folder is not empty.");
           #else
             Crash::forceHalt("Ex011");
           #endif
         }
       }
     }
     // Create the swap folder
     SD.mkdir("/swap");
     // Check to make sure that the swap folder was created
     Swap::ready();
   }
String Swap::read (String name) static
Returns the value of the requested SWAP object.
Definition at line 129 of file swap.cpp.
References Crash::forceHalt(), GetPath(), and ready().
Referenced by Stack::dump(), Parse::Opcode::IO::Files::FILEWRITE(), Parse::Opcode::Logic::IFE(), Parse::Opcode::Logic::IFNE(), Stack::pop(), Parse::Opcode::IO::PRINTV(), Stack::push(), and Tokenizer::TKgetToken().
   {
     // Make sure that swap is ready
     Swap::ready();
     // Check for special compile-time variables
     if(name == "$bootver")
     {
       return "v0.2.0a";
     }
     #ifdef SWAP_CONST_BOOL
       else if(name == "$CONST_true")
       {
         return "true";
       }
       else if(name == "$CONST_false")
       {
         return "false";
       }
     #endif
     #ifdef SWAP_CONST_NUM
       else if(name == "$CONST_1")
       {
         return "1";
       }
       else if(name == "$CONST_2")
       {
         return "2";
       }
       else if(name == "$CONST_3")
       {
         return "3";
       }
       else if(name == "$CONST_4")
       {
         return "4";
       }
       else if(name == "$CONST_5")
       {
         return "5";
       }
       else if(name == "$CONST_6")
       {
         return "6";
       }
       else if(name == "$CONST_7")
       {
         return "7";
       }
       else if(name == "$CONST_8")
       {
         return "8";
       }
       else if(name == "$CONST_9")
       {
         return "9";
       }
       else if(name == "$CONST_0")
       {
         return "0";
       }
     #endif
     #ifdef SWAP_CONST_CHAR
       else if(name.startsWith("$CONST_CHAR_"))
     {
       char cnst;
       sscanf(name.c_str(), "$CONST_CHAR_%c", &cnst);
       String result = String(cnst);
       return result;
     }
     #endif
     else if(name == "$FEAT_SWAP_CONST")
     {
       #ifdef SWAP_CONST_BOOL
         #ifdef SWAP_CONST_NUM
           return "true";
         #endif
       #endif
       return "false";
     }
     else if(name == "$FEAT_IO_Serial")
     {
       #ifdef IO_LOG_SERIAL
         return "true";
       #endif
       return "false";
     }
     else if(name == "$FEAT_IO_SD")
     {
       #ifdef IO_LOG_SD
         return "true";
       #endif
       return "false";
     }
     else if(name == "$FEAT_IO_LCD")
     {
       #ifdef IO_LOG_LCD
         return "true";
       #endif
       return "false";
     }
     else if(name == "$FEAT_CORE_STACK")
     {
       #ifdef CORE_STACK
         return "true";
       #endif
       return "false";
     }
     else if(name.startsWith("$PIN"))
     {
       int nPin = 0;
       sscanf(name.c_str(), "$PIN%02d", &nPin);
       pinMode(nPin, INPUT);
       String result = String(digitalRead(nPin));
       return result;
     }
     // Check to see if variable exists
     if(!SD.exists(Swap::GetPath(name)))
     {
       // It doesn't, so crash the system
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("Swap variable already exists in swap space.");
       #else
         Crash::forceHalt("Ex014");
       #endif
     }
     // Create IO handle
     File readSwap = SD.open(Swap::GetPath(name));
     // Check to see if IO handle was created
     if(readSwap)
     {
       // Create buffer
       String result = "";
       while (readSwap.available())
       {
           // Read characters from IO stream
           result += readSwap.read();
       }
       // Close handle
       readSwap.close();
       // Return swap variable value
       return result;
     }
     // IO error, crash system
     #ifdef CRASH_MSG_DETAIL
       Crash::forceHalt("Error opening swapfile on SD card.");
     #else
       Crash::forceHalt("Ex015");
     #endif
   }
void Swap::ready () static
Checks to see if the SWAP has been initialized. If not, it forces a system crash with swapcrash().
Definition at line 314 of file swap.cpp.
References Crash::forceHalt().
Referenced by create(), init(), read(), sdelete(), and update().
   {
     // Check if swap was initialized
     if(SD.exists("/swap"))
     {
       return;
     }
     // Swap not found, crash system
     #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Swap directory not found.");
         #else
           Crash::forceHalt("Ex017");
         #endif
   }
void Swap::sdelete (String name) static
Removes the requested SWAP object from the SWAP space.
Definition at line 293 of file swap.cpp.
References Crash::forceHalt(), GetPath(), and ready().
Referenced by Parse::Opcode::System::SWAP::DELETE(), and update().
   {
     // Make sure swap is ready
     Swap::ready();
     // Check to see if file exists
     if(SD.exists(Swap::GetPath(name)))
     {
       // Remove file
       SD.remove(Swap::GetPath(name));
       return;
     }
     // IO error, crash the system
     #ifdef CRASH_MSG_DETAIL
       Crash::forceHalt("Error deleting swap file on SD card.");
     #else
       Crash::forceHalt("Ex016");
     #endif
   }
void Swap::update (String name, String value) static
Replaces the requested SWAP object with the given value.
Definition at line 281 of file swap.cpp.
References create(), ready(), and sdelete().
Referenced by Parse::Opcode::Var::Strings::ADDS(), Parse::Opcode::IO::Files::FILEREAD(), Parse::Opcode::Var::Strings::GETC(), Stack::pop(), Stack::push(), and Parse::Opcode::System::SWAP::SET().
   {
     // Make sure swap is ready
     Swap::ready();
     // Delete old value
     Swap::sdelete(name);
     // Create new value
     Swap::create(name, value);
   }
The documentation for this class was generated from the following files:
src/swap.h
src/swap.cpp