Octoduino: Core Class Reference
Core Class Reference
#include <core.h>
Static Public Member Functions
static void init ()
Detailed Description
Definition at line 11 of file core.h.
Member Function Documentation
void Core::init () static
Initializes a task manager to control all processes
Definition at line 23 of file core.cpp.
References Swap::init(), and Task::step().
Referenced by setup().
   {
     // Pre-req for SD class
     pinMode(10, OUTPUT);
     //Open SD card
     SD.begin(4);
     // Initialize SWAP
     Swap::init();
     //Begin parsing the PARSEBASIC main script
     Serial.println("Starting task manager...");
     #ifndef CORE_STACKSIZE
       Task stack[4];
     #else
       Task stack[CORE_STACKSIZE];
     #endif
     int _stackcounter = -1;
     Serial.println("Loading system tasks.");
     // Initialize class objects
     _stackcounter++;
     stack[_stackcounter] = MEMCHECK(_stackcounter);
     _stackcounter++;
     stack[_stackcounter] = Parser(_stackcounter);
     _stackcounter++;
     stack[_stackcounter] = oEthernet(_stackcounter);
     //_stackcounter++;
     //stack[_stackcounter] = new Firmata(_stackcounter);
     // Init class objects
     for(int i = -1; i <= _stackcounter; i++)
     {
       stack[i].step();
     }
     // Loop step() class objects
     while(true)
     {
       for(int i = -1; i <= _stackcounter; i++)
       {
         stack[i].step();
       }
     }
     // Included for debugging purposes
     // Parse::start("/boot.pba");
   }
The documentation for this class was generated from the following files:
src/core.h
src/core.cpp