Octoduino: Tokenizer Class Reference
Tokenizer Class Reference
#include <tokenizer.h>
Static Public Member Functions
static String TKgetToken (String line, int tokenIndex)
Detailed Description
Definition at line 11 of file tokenizer.h.
Member Function Documentation
String Tokenizer::TKgetToken (String line, int tokenIndex) static
Parses a given PB line and returns the token found at the given token index.
Definition at line 18 of file tokenizer.cpp.
References Swap::read(), and Output::write().
Referenced by Parse::run().
     {
         // Create buffer for output
         String resultToken = "";
         // Initialize index counters
         int counter = -1;
         int tcounter = -1;
         // Trim whitespace on input
         line.trim();
         // Set maximums
         int length = line.length();
         // State variables
         boolean isend = false;
         bool isstring = false;
         // Token loop
         while(true)
         {
             tcounter++;
             // Char loop
             while(true)
             {
                 counter++;
                 // Check char pointer against maximum
                 if(counter >= length - 1)
                 {
                     isend = true;
                     break;
                 }
                 // Check for instruction terminator
                 else if(line.charAt(counter == ';'))
                 {
                     isend = true;
                     break;
                 }
                 // Check for start or end of string literal
                 else if(line.charAt(counter == '"'))
                 {
                     if(isstring)
                     {
                         isstring = false;
                     }
                     else
                     {
                         isstring = true;
                     }
                 }
                 // Check for token separator
                 else if(line.charAt(counter) == ' ')
                 {
                     if(isstring)
                     {
                         // Do nothing because we are inside a string
                     }
                     else
                     {
                         break;
                     }
                 }
                 // No special instructions, record char at pointer
                 else
                 {
                     resultToken = resultToken + line.charAt(counter);
                 }
             }
             // Check current token against desired token index
             if(tcounter == tokenIndex)
             {
                 // Check to see if it is a var reference
                 if(resultToken.startsWith("*"))
                 {
                     resultToken.replace("*","");
                     resultToken = Swap::read(resultToken);
                 }
                 return resultToken;
             }
             // Check if end of string
             else if(isend == true)
             {
                 Output::write("Error in tokenizer: unknown token");
                 resultToken = "TKERROR";
                 return resultToken;
             }
             // Clear token buffer and restart loop on next token
             else
             {
                 resultToken = "";
             }
         }
         // Token index not found, send error
         Output::write("Error in tokenizer: argument index not found");
         resultToken = "TKERROR";
         return resultToken;
     }
The documentation for this class was generated from the following files:
src/tokenizer.h
src/tokenizer.cpp