Octoduino: Parse::Opcode::Var::Strings Class Reference
Parse::Opcode::Var::Strings Class Reference
#include <pbparse.h>
Static Public Member Functions
static void ADDS (String _s1, String _s2, String _store)
static void GETC (String _srg, String _rchar, String _store)
Detailed Description
Definition at line 53 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::Var::Strings::ADDS (String _s1, String _s2, String _store) static
Adds two strings together and stores them in a new variable.
Definition at line 221 of file pbparse.cpp.
References Swap::update().
Referenced by Parse::run().
         {
           Swap::update(_store, _s1 + _s2);
         }
void Parse::Opcode::Var::Strings::GETC (String _srg, String _rchar, String _store) static
Gets the character from a string at specified index and stores it in SWAP.
Definition at line 228 of file pbparse.cpp.
References Swap::update().
Referenced by Parse::run().
         {
           int _cindex = _rchar.toInt();
           Swap::update(_store, String(_srg.charAt(_cindex)));
         }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp