Octoduino: Parse::Opcode::Logic Class Reference
Parse::Opcode::Logic Class Reference
#include <pbparse.h>
Static Public Member Functions
static void IFE (String _op1, String _op2, String _sFile)
static void IFNE (String _op1, String _op2, String _sFile)
Detailed Description
Definition at line 62 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::Logic::IFE (String _op1, String _op2, String _sFile) static
Checks if the given arguments are equal. If they are, run EXTLOAD on the given script file. If not, ignore and continue.
Definition at line 257 of file pbparse.cpp.
References Swap::read(), and Parse::start().
Referenced by Parse::run().
       {
         if(Swap::read(_op1) == Swap::read(_op2))
         {
           Parse::start(_sFile);
         }
       }
void Parse::Opcode::Logic::IFNE (String _op1, String _op2, String _sFile) static
Checks if the given arguments are not equal. If they are not equal, run EXTLOAD on the given script file. If they are equal, ignore and continue.
Definition at line 269 of file pbparse.cpp.
References Swap::read(), and Parse::start().
Referenced by Parse::run().
         {
             if (Swap::read(_op1) != Swap::read(_op2))
             {
                 Parse::start(_sFile);
             }
         }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp