Octoduino: Stack Class Reference
Stack Class Reference
#include <stack.h>
Static Public Member Functions
static String dump ()
static void init ()
static void pop (String filepath)
static void push (String filepath)
Detailed Description
Definition at line 11 of file stack.h.
Member Function Documentation
String Stack::dump () static
Returns a dump of the stack.
Definition at line 48 of file stack.cpp.
References Swap::read().
   {
     String dump = "";
     #ifdef CORE_STACK
       dump = Swap::read("OCTOSTACK");
     #endif
     return dump;
   }
void Stack::init () static
Initializes the stack object within the SWAP storage area.
Definition at line 17 of file stack.cpp.
References Swap::create().
   {
     #ifdef CORE_STACK
       Swap::create("OCTSTACK","");
     #endif
   }
void Stack::pop (String filepath) static
Removes the highest instance of the requested program from the stack object.
Definition at line 37 of file stack.cpp.
References Swap::read(), and Swap::update().
Referenced by Parse::start().
   {
     #ifdef CORE_STACK
       String stackvar = Swap::read("OCTSTACK");
       stackvar.remove(stackvar.lastIndexOf(filepath), filepath.length());
       Swap::update("OCTSTACK", stackvar);
     #endif
   }
void Stack::push (String filepath) static
Pushes a new layer onto the stack.
Definition at line 26 of file stack.cpp.
References Swap::read(), and Swap::update().
Referenced by Parse::start().
   {
     #ifdef CORE_STACK
       String result = " -> ";
       result = Swap::read("OCTSTACK") + result + filepath;
       Swap::update("OCTSTACK", result);
     #endif
   }
The documentation for this class was generated from the following files:
src/stack.h
src/stack.cpp