Octoduino: Output Class Reference
Output Class Reference
#include <output.h>
Static Public Member Functions
static void init ()
static void write (String msg)
Detailed Description
Definition at line 15 of file output.h.
Member Function Documentation
void Output::init () static
Initializes the output stream(s). The included streams are determined at compile-time to minimize memory use. See build options docs page.
Definition at line 22 of file output.cpp.
References Crash::forceHalt(), and ch_Serial::init().
Referenced by setup().
   {
     // Initialize channels
     if(ch_Serial::init() != 0)
     {
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("Error initializing Serial output channel.");
       #else
         Crash::forceHalt("Ex001");
       #endif
     }
     #ifdef IO_LOG_SD
       if(ch_SD::init() != 0)
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Error initializing SD log output channel.");
         #else
           Crash::forceHalt("Ex002");
         #endif
       }
     #endif
     #ifdef IO_LOG_LCD
       if(ch_LCD::init() != 0)
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Error initializing LCD output channel.");
         #else
           Crash::forceHalt("Ex003");
         #endif
       }
     #endif
   }
void Output::write (String msg) static
Writes a String to all initialized output streams.
Definition at line 57 of file output.cpp.
References Crash::forceHalt(), and ch_Serial::write().
Referenced by Core::init(), Parse::Opcode::IO::NEWPRINT(), Parse::Opcode::IO::PRINT(), Parse::Opcode::IO::PRINTV(), setup(), and Tokenizer::TKgetToken().
   {
     // Get time (HH:MM:SS)
     unsigned long ms = millis();
     unsigned long mi = ms / 1000;
     ms = ms % 1000;
     unsigned long hr = mi / 60;
     mi = mi % 60;
     char buffer[12] = "";
     sprintf(buffer, "[%ld:%ld:%ld] ", hr, mi, ms);
     String timestamp = buffer;
     timestamp.trim();
     ch_Serial::write(timestamp, msg);
     #ifdef IO_LOG_SD
       if(ch_SD::write(timestamp, msg) != 0)
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Error writing to log on SD card.");
         #else
           Crash::forceHalt("Ex004");
         #endif
       }
     #endif
     #ifdef IO_LOG_LCD
       if(ch_LCD::write(timestamp, msg) != 0)
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Error outputting to LCD screen");
         #else
           Crash::forceHalt("Ex005");
         #endif
       }
     #endif
   }
The documentation for this class was generated from the following files:
src/output.h
src/output.cpp