Octoduino: Parser Class Reference
Parser Class Reference
#include <pbparse.h>
Public Member Functions
void init ()
Parser (int _ID)
void step ()
Public Member Functions inherited from Task
int getID ()
Task ()
Task (int _ID)
Additional Inherited Members
Protected Attributes inherited from Task
int taskID
Detailed Description
Definition at line 14 of file pbparse.h.
Constructor & Destructor Documentation
Parser::Parser (int _ID)
Definition at line 19 of file pbparse.cpp.
                         : Task(_ID)
   {
     // Nothing to instance here
   }
Member Function Documentation
void Parser::init () virtual
Reimplemented from Task.
Definition at line 23 of file pbparse.cpp.
References Crash::forceHalt(), and Stack::push().
   {
     this->source = SD.open(F("/boot.pba"));
     if(!source)
     {
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("PB runner could not open file.");
       #else
         Crash::forceHalt("Ex006");
       #endif
     }
     Stack::push(F("/boot.pba"));
   }
void Parser::step () virtual
Reimplemented from Task.
Definition at line 36 of file pbparse.cpp.
References Crash::forceHalt(), and Parse::run().
   {
     if(!this->source.available())
     {
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("End of script file.");
       #else
         Crash::forceHalt("Ex000");
       #endif
     }
     String cmd = "";
     const char terminator = ';';
     while(char(this->source.peek()) != terminator)
     {
       cmd += char(source.read());
     }
     this->source.read();
     Parse::run(cmd);
   }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp