Octoduino: Parse::Opcode::IO::Files Class Reference
Parse::Opcode::IO::Files Class Reference
#include <pbparse.h>
Static Public Member Functions
static void FILEREAD (String _filepath, String _var)
static void FILEWRITE (String _filepath, String _var)
Detailed Description
Definition at line 43 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::IO::Files::FILEREAD (String _filepath, String _var) static
Reads the requested file into SWAP buffer.
Definition at line 190 of file pbparse.cpp.
References Crash::forceHalt(), and Swap::update().
Referenced by Parse::run().
         {
           if(!SD.exists(_filepath))
           {
             #ifdef CRASH_MSG_DETAIL
                 Crash::forceHalt("File does not exist on SD card.");
                 #else
                 Crash::forceHalt("Ex009");
                 #endif
           }
           String _readbuf = "";
           File _file = SD.open(_filepath, FILE_WRITE);
           if(!_file)
           {
             #ifdef CRASH_MSG_DETAIL
                 Crash::forceHalt("Error reading from file on SD card.");
                 #else
                 Crash::forceHalt("Ex010");
                 #endif
           }
           while(_file.available())
           {
             _readbuf = _readbuf + _file.read();
           }
           Swap::update(_var, _readbuf);
           _file.close();
         }
void Parse::Opcode::IO::Files::FILEWRITE (String _filepath, String _var) static
Writes the requested string to an open file on SD card.
Definition at line 169 of file pbparse.cpp.
References Crash::forceHalt(), and Swap::read().
Referenced by Parse::run().
         {
           File _file = SD.open(_filepath, FILE_WRITE);
           if(_file)
           {
             _file.println(Swap::read(_var).c_str());
           }
           else
           {
             #ifdef CRASH_MSG_DETAIL
               Crash::forceHalt("Error writing to file on SD card.");
             #else
                 Crash::forceHalt("Ex008");
                 #endif
           }
           _file.flush();
           _file.close();
         }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp