Octoduino: Parse::Opcode::System Class Reference
Parse::Opcode::System Class Reference
#include <pbparse.h>
Classes
class SWAP
Static Public Member Functions
static void END ()
static void EXTLOAD (String _filepath)
static void WAIT (String _pTime)
Detailed Description
Definition at line 60 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::System::END () static
Halts the system in a clean manner.
Definition at line 252 of file pbparse.cpp.
References Crash::forceHalt().
Referenced by Parse::run().
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Program has been terminated by the script file.");
         #else
           Crash::forceHalt("Ex000");
         #endif
       }
void Parse::Opcode::System::EXTLOAD (String _filepath) static
Spawns a new runner task from the specified PB script file.
Definition at line 244 of file pbparse.cpp.
References Crash::forceHalt().
Referenced by Parse::run().
       {
         //Parse::start(_filepath);
         Crash::forceHalt(F("EXTLOAD has been temporarily disabled."));
       }
void Parse::Opcode::System::WAIT (String _pTime) static
Pauses the system for a specified amount of time.
Definition at line 237 of file pbparse.cpp.
Referenced by Parse::run().
       {
         delay(int(_pTime.c_str()));
       }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp