Octoduino: Parse Class Reference
Parse Class Reference
#include <pbparse.h>
Classes
class Opcode
Static Public Member Functions
static void run (String line)
static void start (String filename)
Detailed Description
Definition at line 11 of file pbparse.h.
Member Function Documentation
void Parse::run (String line) static
Parses one line of trimmed PB code.
Definition at line 50 of file pbparse.cpp.
References Parse::Opcode::Var::Strings::ADDS(), Parse::Opcode::System::SWAP::CREATESWAP(), Parse::Opcode::System::SWAP::DELETE(), Parse::Opcode::System::END(), Parse::Opcode::System::EXTLOAD(), Parse::Opcode::IO::Files::FILEREAD(), Parse::Opcode::IO::Files::FILEWRITE(), Crash::forceHalt(), Parse::Opcode::Var::Strings::GETC(), Parse::Opcode::Logic::IFE(), Parse::Opcode::Logic::IFNE(), Parse::Opcode::IO::Ports::IO(), Parse::Opcode::System::SWAP::NEW(), Parse::Opcode::IO::NEWPRINT(), Parse::Opcode::IO::PRINT(), Parse::Opcode::IO::PRINTV(), Parse::Opcode::System::SWAP::SET(), Tokenizer::TKgetToken(), and Parse::Opcode::System::WAIT().
Referenced by start().
   {
     line.trim();
     if(line.startsWith("//"))
     {
       // Do nothing, this is a comment
     }
     else
     {
       String opcode = Tokenizer::TKgetToken(line, 0);
       if(opcode == "PRINT") Parse::Opcode::IO::PRINT(Tokenizer::TKgetToken(line, 1));
       else if(opcode == "PRINTV") Parse::Opcode::IO::PRINTV(Tokenizer::TKgetToken(line, 1));
       else if(opcode == "ADDS") Parse::Opcode::Var::Strings::ADDS(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2), Tokenizer::TKgetToken(line, 3));
       else if (opcode == "GETC") Parse::Opcode::Var::Strings::GETC(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2), Tokenizer::TKgetToken(line, 3));
       else if(opcode == "NEWPRINT") Parse::Opcode::IO::NEWPRINT();
       else if(opcode == "WAIT") Parse::Opcode::System::WAIT(Tokenizer::TKgetToken(line, 1));
       else if(opcode == "IFE") Parse::Opcode::Logic::IFE(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2), Tokenizer::TKgetToken(line, 3));
       else if(opcode == "IFNE") Parse::Opcode::Logic::IFNE(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2), Tokenizer::TKgetToken(line, 3));
       else if(opcode == "CREATESWAP") Parse::Opcode::System::SWAP::CREATESWAP();
       else if(opcode == "IO") Parse::Opcode::IO::Ports::IO(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2));
       else if(opcode == "NEW") Parse::Opcode::System::SWAP::NEW(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2));
       else if(opcode == "DELETE") Parse::Opcode::System::SWAP::DELETE(Tokenizer::TKgetToken(line, 1));
       else if(opcode == "SET") Parse::Opcode::System::SWAP::SET(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2));
       else if(opcode == "EXTLOAD") Parse::Opcode::System::EXTLOAD(Tokenizer::TKgetToken(line, 1));
       else if(opcode == "FILEWRITE") Parse::Opcode::IO::Files::FILEWRITE(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2));
       else if(opcode == "FILEREAD") Parse::Opcode::IO::Files::FILEREAD(Tokenizer::TKgetToken(line, 1), Tokenizer::TKgetToken(line, 2));
       else if(opcode == "END") Parse::Opcode::System::END();
       else
       {
         #ifdef CRASH_MSG_DETAIL
           Crash::forceHalt("Error, unrecognized command.");
         #else
           Crash::forceHalt("Ex007");
         #endif
       }
     }
   };
void Parse::start (String filename) static
Creates a runner to begin execution of a new source file.
Definition at line 21 of file pbparse.cpp.
References Crash::forceHalt(), Stack::pop(), Stack::push(), and run().
Referenced by Parse::Opcode::System::EXTLOAD(), Parse::Opcode::Logic::IFE(), Parse::Opcode::Logic::IFNE(), and Core::init().
   {
     File source = SD.open(filename.c_str());
     if(!source)
     {
       #ifdef CRASH_MSG_DETAIL
         Crash::forceHalt("PB runner could not open file.");
       #else
         Crash::forceHalt("Ex006");
       #endif
     }
     Stack::push(filename);
     const char terminator = ';';
     while(source.available())
     {
       String cmd = "";
       while(char(source.peek()) != terminator)
       {
         cmd += char(source.read());
       }
       source.read();
       Parse::run(cmd);
     }
     source.close();
     Stack::pop(filename);
   }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp