Octoduino: Crash Class Reference
Crash Class Reference
#include <crash.h>
Static Public Member Functions
static void forceHalt (String msg)
Detailed Description
Definition at line 11 of file crash.h.
Member Function Documentation
void Crash::forceHalt (String msg) static
Forces a system halt (or reset if defined by compiler).
Definition at line 15 of file crash.cpp.
Referenced by Swap::create(), Parse::Opcode::System::END(), Parse::Opcode::IO::Files::FILEREAD(), Parse::Opcode::IO::Files::FILEWRITE(), Output::init(), Swap::init(), Swap::read(), Swap::ready(), Parse::run(), Swap::sdelete(), Parse::start(), and Output::write().
   {
     // Bad idea, may cause crash loop
     // Output::write(msg);
     Serial.println("");
     Serial.print("Error: ");
     Serial.println(msg);
     Serial.print("Stack dump: ");
     // Serial.println(Stack::dump());
     #ifdef CRASH_REBOOT
       Serial.println("Rebooting system...");
       asm volatile ("  jmp 0");
     #endif
     Serial.println("Halting system...");
     pinMode(13, OUTPUT);
     while(true)
     {
       digitalWrite(13, HIGH);
       delay(250);
       digitalWrite(13, LOW);
       delay(250);
     }
   }
The documentation for this class was generated from the following files:
src/crash.h
src/crash.cpp