Octoduino: Parse::Opcode::IO Class Reference
Parse::Opcode::IO Class Reference
#include <pbparse.h>
Classes
class Files
class Ports
Static Public Member Functions
static void NEWPRINT ()
static void PRINT (String _msg)
static void PRINTV (String _var)
Detailed Description
Definition at line 19 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::IO::NEWPRINT () static
Prints a new line to the output stream.
Definition at line 105 of file pbparse.cpp.
References Output::write().
Referenced by Parse::run().
       {
         Output::write("\n");
       }
void Parse::Opcode::IO::PRINT (String _msg) static
Prints a string to all configured output buffers.
Definition at line 91 of file pbparse.cpp.
References Output::write().
Referenced by Parse::run().
       {
         Output::write(_msg);
       }
void Parse::Opcode::IO::PRINTV (String _var) static
Prints a SWAP variable to all configured output buffers.
Definition at line 98 of file pbparse.cpp.
References Swap::read(), and Output::write().
Referenced by Parse::run().
       {
         Output::write(Swap::read(_var));
       }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp