Octoduino: Parse::Opcode::System::SWAP Class Reference
Parse::Opcode::System::SWAP Class Reference
#include <pbparse.h>
Static Public Member Functions
static void CREATESWAP ()
static void DELETE (String _name)
static void NEW (String _name, String _value)
static void SET (String name, String _value)
Detailed Description
Definition at line 53 of file pbparse.h.
Member Function Documentation
void Parse::Opcode::System::SWAP::CREATESWAP () static
DEPRECIATED: creates the swap directory.
Definition at line 225 of file pbparse.cpp.
Referenced by Parse::run().
         {
           // Do nothing since this is handled by Core::
           //swapinit();
         }
void Parse::Opcode::System::SWAP::DELETE (String _name) static
Deletes a SWAP variable.
Definition at line 240 of file pbparse.cpp.
References Swap::sdelete().
Referenced by Parse::run().
         {
           Swap::sdelete(_name);
         }
void Parse::Opcode::System::SWAP::NEW (String _name, String _value) static
Creates a new SWAP variable.
Definition at line 233 of file pbparse.cpp.
References Swap::create().
Referenced by Parse::run().
         {
           Swap::create(_name, _value);
         }
void Parse::Opcode::System::SWAP::SET (String _name, String _value) static
Assigns a SWAP variable a new value.
Definition at line 247 of file pbparse.cpp.
References Swap::update().
Referenced by Parse::run().
         {
           Swap::update(_name, _value);
         }
The documentation for this class was generated from the following files:
src/pbparse.h
src/pbparse.cpp