Octoduino: src/main.ino File Reference
main.ino File Reference
#include <SD.h>
#include <SPI.h>
#include "core.h"
#include "output.h"
Macros
#define BUILDPIPE_BNUM "local"
Functions
void loop ()
void setup ()
Macro Definition Documentation
#define BUILDPIPE_BNUM "local"
Definition at line 15 of file main.ino.
Referenced by setup().
Function Documentation
void loop ()
Loop (required by Arduino). Not used.
Definition at line 37 of file main.ino.
 {
   // Do nothing until power is cut
 }
void setup ()
Set up the system (required by Arduino).
Definition at line 21 of file main.ino.
References BUILDPIPE_BNUM, Core::init(), Output::init(), and Output::write().
 {
   // Status LED
   pinMode(13, OUTPUT);
   // Initialize output class
   Output::init();
   Output::write("Octoduino v0.1.3. Build: " + BUILDPIPE_BNUM);
   Output::write("Copyright 2015 - NETponents");
   Output::write("Distributed under the GNU GPL v2.0 license");
   Output::write("Commercial use with this build of Octoduino is prohibited");
   // Start the bootloader
   Core::init();
 }