Octoduino: lib/output/output.h File Reference
output.h File Reference
Functions
void outinit ()
void outwrite (String msg)
Function Documentation
void outinit ()
Initializes the output stream(s). The included streams are determined at compile-time to minimize memory use.
Definition at line 21 of file output.cpp.
Referenced by setup().
 {
   // Initialize text logs on SD card
   #ifdef IO_LOG_SD
     File logger = SD.open("/log.txt");
     if(logger)
     {
       logger.println("Logging started");
       Serial.println("IO Channel: SD [OK]");
     }
     else
     {
       Serial.println("IO Channel: SD [FAIL]");
     }
   #endif
   #ifdef IO_LOG_LCD
     lcd.begin(16, 2);
     lcd.noCursor();
     Serial.println("IO Channel: LCD [OK]");
   #endif
 }
void outwrite (String msg)
Writes a String to all initialized output streams.
Definition at line 45 of file output.cpp.
Referenced by initBootstrap(), PBcrash(), PBparse(), PBstart(), PBstop(), setup(), swapcrash(), swapcreate(), swapdelete(), swapinit(), swapread(), swapready(), and TKgetToken().
 {
   // Get time (HH:MM:SS)
   unsigned long ms = millis();
   unsigned long mi = ms / 1000;
   ms = ms % 1000;
   unsigned long hr = mi / 60;
   mi = mi % 60;
   // Print message to serial
   Serial.print("[");
   Serial.print(hr);
   Serial.print(":");
   Serial.print(mi);
   Serial.print(":");
   Serial.print(ms);
   Serial.print("] ");
   Serial.println(msg);
   // Also print message to logger
   #ifdef IO_LOG_SD
     File logger = SD.open("/log.txt");
     logger.println(msg);
     logger.close();
   #endif
   #ifdef IO_LOG_LCD
     lcd.clear();
     lcd.home();
     lcd.print("[");
     lcd.print(hr);
     lcd.print(":");
     lcd.print(mi);
     lcd.print(":");
     lcd.print(ms);
     lcd.print("] ");
     lcd.setCursor(0, 1);
     lcd.print(msg);
   #endif
 }