Octoduino: lib/pbparse/pbparse.cpp File Reference
pbparse.cpp File Reference
#include <Arduino.h>
#include <SD.h>
#include <SPI.h>
#include "pbparse.h"
#include "swap.h"
#include "output.h"
#include "tokenizer.h"
#include "stack.h"
Functions
void PBcrash ()
void PBparse (String line)
void PBstart (String filename)
void PBstop ()
Function Documentation
void PBcrash (void)
Halts the system forcefully due to a software or hardware error.
Definition at line 214 of file pbparse.cpp.
References outwrite().
Referenced by PBparse(), and PBstart().
 {
   // System has crashed
   // Notify user
   outwrite("ParseBasic parser has encountered an error. Terminating.");
   while(true)
   {
     // Loop until power is reset
   }
 }
void PBparse (String line)
Parses one line of trimmed PB code.
Definition at line 60 of file pbparse.cpp.
References outwrite(), PBcrash(), PBstart(), PBstop(), swapcreate(), swapdelete(), swapinit(), swapread(), swapupdate(), and TKgetToken().
Referenced by PBstart().
 {
   // Check if this line is a comment
   if(line.startsWith("//"))
   {
     //Do nothing, this is a comment
   }
   else
   {
     // Get opcode from instruction
     String opcode = TKgetToken(line, 0);
     // Check opcode against dictionary
     if(opcode == "PRINT")
     {
       outwrite(TKgetToken(line, 1));
     }
     else if(opcode == "PRINTV")
     {
       outwrite(swapread(TKgetToken(line, 1)));
     }
     else if(opcode == "ADDS")
     {
       swapupdate(TKgetToken(line, 3), TKgetToken(line, 1) + TKgetToken(line, 2));
     }
     else if(opcode == "GETC")
     {
       int cindex = TKgetToken(line, 3).toInt();
       swapupdate(TKgetToken(line, 2), String(TKgetToken(line, 1).charAt(cindex)));
     }
     else if(opcode == "NEWPRINT")
     {
       outwrite("\n");
     }
     else if(opcode == "WAIT")
     {
       delay(int(TKgetToken(line, 1).c_str()));
     }
     else if(opcode == "IFE")
     {
       if(swapread(TKgetToken(line, 1)) == swapread(TKgetToken(line, 2)))
       {
         PBstart(TKgetToken(line, 3).c_str());
       }
     }
     else if(opcode == "IFNE")
     {
       if(swapread(TKgetToken(line, 1)) != swapread(TKgetToken(line, 2)))
       {
         PBstart(TKgetToken(line, 3).c_str());
       }
     }
     else if(opcode == "CREATESWAP")
     {
       swapinit();
     }
     else if(opcode == "IO")
     {
       int portn = int(TKgetToken(line, 1).c_str());
       int state = int(TKgetToken(line, 2).c_str());
       pinMode(portn, OUTPUT);
       if(state == '0')
       {
         digitalWrite(portn, LOW);
       }
       else
       {
         digitalWrite(portn, HIGH);
       }
     }
     else if(opcode == "NEW")
     {
       String value = TKgetToken(line, 2);
       if(value == "TKERROR")
       {
         value = "";
       }
       swapcreate(TKgetToken(line, 1), value);
     }
     else if(opcode == "DELETE")
     {
       swapdelete(TKgetToken(line, 1));
     }
     else if(opcode == "SET")
     {
       swapupdate(TKgetToken(line, 1), TKgetToken(line, 2));
     }
     else if(opcode == "EXTLOAD")
     {
       PBstart(TKgetToken(line, 1).c_str());
     }
     else if(opcode == "FILEWRITE")
     {
       File extfile = SD.open(TKgetToken(line, 1), FILE_WRITE);
       if(extfile)
       {
         extfile.println(swapread(TKgetToken(line, 2)).c_str());
       }
       else
       {
         PBcrash();
       }
       extfile.close();
     }
     else if(opcode == "FILEREAD")
     {
       if (SD.exists(TKgetToken(line, 1)))
       {
         File extfile = SD.open(TKgetToken(line, 1), FILE_WRITE);
         if(extfile)
         {
           String readvar = "";
           while (extfile.available())
           {
             readvar = readvar + extfile.read();
           }
           swapupdate(TKgetToken(line, 2), readvar);
         }
         else
         {
           PBcrash();
         }
         extfile.close();
       }
       else
       {
         PBcrash();
       }
     }
     else if(opcode == "END")
     {
       // Program has requested that execution end
       PBstop();
     }
     else
     {
       PBcrash();
     }
   }
 }
void PBstart (String filename)
Creates a runner to begin execution of a new source file.
Definition at line 20 of file pbparse.cpp.
References outwrite(), PBcrash(), PBparse(), stackpop(), and stackpush().
Referenced by initBootstrap(), and PBparse().
 {
   // Open file handle to source file
   File bootloader = SD.open(filename.c_str());
   // Check to see if file handle opened
   if(bootloader)
   {
     // Push it onto the stack
     stackpush(filename);
     // Instruction terminator
     char terminator = ';';
     while (bootloader.available())
     {
       // Clear instruction buffer
       String cmd = "";
       // Read until you hit instruction terminator
       while (char(bootloader.peek()) != terminator)
       {
         cmd += bootloader.read();
       }
       // Read one more time to include instruction terminator
       cmd += bootloader.read();
       // Send the instruction for parsing
       PBparse(cmd);
     }
     // Close file handle
     bootloader.close();
     // Pop it from the stack
     stackpop(filename);
   }
   else
   {
     // File handle could not be opened, crash the system
     outwrite("Error in PBparse: Runner could not open requested file.");
     PBcrash();
   }
 }
void PBstop (void)
Halts the system safely by request of the program.
Definition at line 202 of file pbparse.cpp.
References outwrite().
Referenced by PBparse().
 {
   // Halt the program
   outwrite("Program has finished. Terminating.");
   while(true)
   {
     // Loop until power is reset
   }
 }