Octoduino: src/pbparse.h File Reference
pbparse.h File Reference
Functions
void PBstart (String filename)
void PBparse (String line)
void PBcrash (void)
void PBstop (void)
Function Documentation
void PBcrash (void)
Halts the system forcefully due to a software or hardware error.
References outwrite().
Referenced by PBparse(), and PBstart().
void PBparse (String line)
Parses one line of trimmed PB code.
References outwrite(), PBcrash(), PBstart(), PBstop(), swapcreate(), swapdelete(), swapinit(), swapread(), swapupdate(), and TKgetToken().
Referenced by PBstart().
void PBstart (String filename)
Creates a runner to begin execution of a new source file.
References outwrite(), PBcrash(), PBparse(), stackpop(), and stackpush().
Referenced by initBootstrap(), and PBparse().
void PBstop (void)
Halts the system safely by request of the program.
References outwrite().
Referenced by PBparse().