Octoduino: src/stack.h File Reference
stack.h File Reference
Functions
void stackinit ()
void stackpush (String filepath)
void stackpop (String filepath)
String stackdump ()
Function Documentation
String stackdump ()
Returns a dump of the stack.
void stackinit ()
Initializes the stack object within the SWAP storage area.
References swapcreate().
void stackpop (String filepath)
Removes the highest instance of thee requested program from the stack object.
References swapread(), and swapupdate().
Referenced by PBstart().
void stackpush (String filepath)
Pushes a new layer onto the stack.
References swapread(), and swapupdate().
Referenced by PBstart().