Octoduino: lib/stack/stack.cpp File Reference
stack.cpp File Reference
#include <Arduino.h>
#include <SD.h>
#include <SPI.h>
#include "swap.h"
Functions
String stackdump ()
void stackinit ()
void stackpop (String filepath)
void stackpush (String filepath)
Function Documentation
String stackdump ()
Returns a dump of the stack.
Definition at line 47 of file stack.cpp.
 {
   String dump = "";
   #ifdef CORE_STACK
     dump = "";
   #endif
   return dump;
 }
void stackinit ()
Initializes the stack object within the SWAP storage area.
Definition at line 16 of file stack.cpp.
References swapcreate().
 {
   #ifdef CORE_STACK
     swapcreate("OCTSTACK","");
   #endif
 }
void stackpop (String filepath)
Removes the highest instance of thee requested program from the stack object.
Definition at line 36 of file stack.cpp.
References swapread(), and swapupdate().
Referenced by PBstart().
 {
   #ifdef CORE_STACK
     String stackvar = swapread("OCTSTACK");
     stackvar.remove(stackvar.lastIndexOf(filepath), filepath.length());
     swapupdate("OCTSTACK", stackvar);
   #endif
 }
void stackpush (String filepath)
Pushes a new layer onto the stack.
Definition at line 25 of file stack.cpp.
References swapread(), and swapupdate().
Referenced by PBstart().
 {
   #ifdef CORE_STACK
     String result = " -> ";
     result = swapread("OCTSTACK") + result + filepath;
     swapupdate("OCTSTACK", result);
   #endif
 }