Octoduino: src/swap.cpp File Reference
swap.cpp File Reference
#include <Arduino.h>
#include <SD.h>
#include <SPI.h>
#include "swap.h"
#include "output.h"
Functions
void swapinit ()
void clearFolder (File fldr)
String swapGetPath (String name)
void swapcreate (String name, String value)
String swapread (String name)
void swapupdate (String name, String value)
void swapdelete (String name)
void swapcrash ()
void swapready ()
Function Documentation
void clearFolder (File fldr)
Recursivly removes all files from within a folder, then deletes it and returns.
References clearFolder().
Referenced by clearFolder(), and swapinit().
void swapcrash ()
Crashes the system due to a SWAP error.
References outwrite().
Referenced by swapcreate(), swapdelete(), swapinit(), swapread(), and swapready().
void swapcreate (String name, String value)
Creates a new swap object and assigns it the given value.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), stackinit(), and swapupdate().
void swapdelete (String name)
Removes the requested SWAP object from the SWAP space.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), and swapupdate().
String swapGetPath (String name)
Gets the full SWAP path of the requested variable.
Referenced by swapcreate(), swapdelete(), and swapread().
void swapinit ()
Initializes the SWAP area on the SD card.
References clearFolder(), outwrite(), swapcrash(), and swapready().
Referenced by PBparse().
String swapread (String name)
Returns the value of the requested SWAP object.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), stackpop(), and stackpush().
void swapready ()
Checks to see if the SWAP has been initialized. If not, it forces a system crash with swapcrash().
References outwrite(), and swapcrash().
Referenced by swapcreate(), swapdelete(), swapinit(), swapread(), and swapupdate().
void swapupdate (String name, String value)
Replaces the requested SWAP object with the given value.
References swapcreate(), swapdelete(), and swapready().
Referenced by PBparse(), stackpop(), and stackpush().