Octoduino: lib/swap/swap.h File Reference
swap.h File Reference
Functions
void clearFolder (File fldr)
void swapcrash ()
void swapcreate (String name, String value)
void swapdelete (String name)
String swapGetPath (String name)
void swapinit ()
String swapread (String name)
void swapready ()
void swapupdate (String name, String value)
Function Documentation
void clearFolder (File fldr)
Recursivly removes all files from within a folder, then deletes it and returns.
Definition at line 43 of file swap.cpp.
References clearFolder().
Referenced by clearFolder(), and swapinit().
 {
   while(true)
   {
     File node = fldr.openNextFile();
     if(!node)
     {
       // No more files found in directory
       break;
     }
     else if(node.isDirectory())
     {
       clearFolder(node);
       SD.rmdir(node.name());
     }
     else
     {
       SD.remove(node.name());
     }
   }
 }
void swapcrash ()
Crashes the system due to a SWAP error.
Definition at line 180 of file swap.cpp.
References outwrite().
Referenced by swapcreate(), swapdelete(), swapinit(), swapread(), and swapready().
 {
   // Notify user of crash
   outwrite("The SWAP module has failed!");
   while(true)
   {
     // Do nothing until system is reset
   }
 }
void swapcreate (String name, String value)
Creates a new swap object and assigns it the given value.
Definition at line 79 of file swap.cpp.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), stackinit(), and swapupdate().
 {
   // Make sure that swap is ready
   swapready();
   // Check to see if variable already exists
   if(SD.exists(swapGetPath(name)))
   {
     // It does, so crash system
     outwrite("Error in SWAP: Tried to create a variable that already exists");
     swapcrash();
   }
   // Create new file handle for new swap file
   File newSwap = SD.open(swapGetPath(name), FILE_WRITE);
   // Check to see if we could open the file
   if (newSwap)
   {
     // Write value of item and close the handle
     newSwap.println(value);
     newSwap.close();
   }
   else
   {
     // IO error, crash the system
     outwrite("Error in SWAP: Could not open variable SWAP file. Check the medium for storage corruption");
     swapcrash();
   }
 }
void swapdelete (String name)
Removes the requested SWAP object from the SWAP space.
Definition at line 162 of file swap.cpp.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), and swapupdate().
 {
   // Make sure swap is ready
   swapready();
   // Check to see if file exists
   if(SD.exists(swapGetPath(name)))
   {
     // Remove file
     SD.remove(swapGetPath(name));
     return;
   }
   // IO error, crash the system
   outwrite("ERR: 0x9");
   swapcrash();
 }
String swapGetPath (String name)
Gets the full SWAP path of the requested variable.
Definition at line 67 of file swap.cpp.
Referenced by swapcreate(), swapdelete(), and swapread().
 {
   // Add parts together
   String swp = "/swap/";
   String ext = ".swp";
   String result = swp + name + ext;
   // Return full filename
   return result;
 }
void swapinit ()
Initializes the SWAP area on the SD card.
Definition at line 17 of file swap.cpp.
References clearFolder(), outwrite(), swapcrash(), and swapready().
Referenced by PBparse().
 {
   // Check to see if swap exists
   if(SD.exists("/swap"))
   {
     // Attempt to remove it
     if(!SD.rmdir("/swap"))
     {
       // SWAP folder is not empty
       File root = SD.open("/swap/");
       clearFolder(root);
       if(SD.exists("/swap"))
       {
         outwrite("Error in SWAP: working directory not cleared.");
         swapcrash();
       }
     }
   }
   // Create the swap folder
   SD.mkdir("/swap");
   // Check to make sure that the swap folder was created
   swapready();
 }
String swapread (String name)
Returns the value of the requested SWAP object.
Definition at line 110 of file swap.cpp.
References outwrite(), swapcrash(), swapGetPath(), and swapready().
Referenced by PBparse(), stackpop(), and stackpush().
 {
   // Make sure that swap is ready
   swapready();
   // Check for special compile-time variables
   if(name == "$bootver")
   {
     return "v0.1.3";
   }
   // Check to see if variable exists
   if(!SD.exists(swapGetPath(name)))
   {
     // It doesn't, so crash the system
     outwrite("ERR: 0x7");
     swapcrash();
   }
   // Create IO handle
   File readSwap = SD.open(swapGetPath(name));
   // Check to see if IO handle was created
   if(readSwap)
   {
     // Create buffer
     String result = "";
     while (readSwap.available())
     {
         // Read characters from IO stream
         result += readSwap.read();
     }
     // Close handle
     readSwap.close();
     // Return swap variable value
     return result;
   }
   // IO error, crash system
   outwrite("ERR: 0x8");
   swapcrash();
 }
void swapready ()
Checks to see if the SWAP has been initialized. If not, it forces a system crash with swapcrash().
Definition at line 192 of file swap.cpp.
References outwrite(), and swapcrash().
Referenced by swapcreate(), swapdelete(), swapinit(), swapread(), and swapupdate().
 {
   // Check if swap was initialized
   if(SD.exists("/swap"))
   {
     return;
   }
   // Swap not found, crash system
   outwrite("ERR: 0x6");
   swapcrash();
 }
void swapupdate (String name, String value)
Replaces the requested SWAP object with the given value.
Definition at line 150 of file swap.cpp.
References swapcreate(), swapdelete(), and swapready().
Referenced by PBparse(), stackpop(), and stackpush().
 {
   // Make sure swap is ready
   swapready();
   // Delete old value
   swapdelete(name);
   // Create new value
   swapcreate(name, value);
 }